### ISSUE TITLE
Drop in frame rate

### ISSUE THREAD

**Issue by OregonPinkRose** [PhilippeKr/TorchLight#1]
More a comment. Tried out the module today. My frames drop from 58 to 32 when I enable this module.

**Comment by PhilippeKr** [comment]
Thanks for the feedback, but I wonder if it is not simply linked to the animations in the tokens, as I see really nothing that would account for such a high consumption of resources. Is the framerate drop just to the enabling of the module, or is it after creating some lights on a map ?

**Comment by OregonPinkRose** [comment]
This is after turning on a torch and turning it off.

**Comment by PhilippeKr** [comment]
Honestly, I'm not sure that I can do anything about this, it's probably caused by the  special effect of the light itself. The best way to check (as I cannot reproduce this at all on my instances) would be to create a similar light on a token without the module and see whether you have the same drop...
