### ISSUE TITLE
Icon offsets need adjusting

### ISSUE THREAD

**Issue by JamzTheMan** [PhilippeKr/TorchLight#13]
I'm currently using the "bottom" setting (mostly because I have mods that probably affect the left/right positions) and there is still some overlap which I believe isn't due to any mods? (This would be the default GM view I think?)

If they could be adjust just down and to the right a few pixels (at least for GM views) it would fit better? Centering for Players is probably ok but I didn't test.

Also, is there a lantern icon available vs the lightbulb? May be more fantasy immersive, I keep forgetting which is torch vs latern 😄 

![image](https://user-images.githubusercontent.com/8051654/107255022-7f668680-69fd-11eb-994c-9181507e79a5.png)

**Comment by JamzTheMan** [comment]
(I just noticed in this pick my Info icons are also overlapping, maybe I do have a mod conflict that is making the standard icons larger?

**Comment by PhilippeKr** [comment]
I think this is due to your standard icons being very large, at least larger than usual. The Token info on the left shouldn't be overlapped either, for example, and you have 4 icons instead of 3 in the left column. This is probably due to other add-ons, unfortunately. This is what it looks like on a standard token.

![Screenshot 2021-02-08 182743](https://user-images.githubusercontent.com/77798281/107257805-5cf35e00-6a3b-11eb-8806-c0af8e167640.png)

Let me know how it goes...

**Comment by PhilippeKr** [comment]
I will close this, assuming that you have found the other setting that interfered.
